"""Initial migration

Revision ID: f666d08601d3
Revises: 
Create Date: 2024-12-17 17:23:50.256168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f666d08601d3'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
    # Создаем таблицу 'item' с колонками 'id', 'name', 'description'
    op.create_table(
        'item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
