version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db/postgres
    volumes:
      - ./app:/app
      - flask_app_static:/app/static
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app_network
    command: >
      sh -c "flask db upgrade || flask db init && flask db migrate -m 'Initial migration' && flask db upgrade && flask run --host=0.0.0.0 --port=4000"


  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  flask_app_static:
  postgres_data:

networks:
  app_network:
    driver: bridge
